server:
  port: 8781

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order-service
  redis:
    database: 0
    host: 127.0.01
    port: 6379
    timeout: 2000
  #zipkin服务所在地址
  zipkin:
    base-url: http://localhost:9411/
  #配置采样百分比 开发环境设置为1 生产环境设计值要小
  sleuth:
    sampler:
      probability: 1

#自定义Ribbon负载均衡策略 IRule下的之类
#如果各个机器的配置一样，则不建议修改策略，用默认的负载均衡策略就可以了（推荐）
#如果各个机器的配置不一样，可以修改负载均衡策略为 WeightedResponseTimeRule 权重策略
#要负载服务名称
#product-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#设置超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
  #Feign默认是不开启Hystrix降级(feign里面自动引入了hystrix)
  hystrix:
    enabled: true

#hystrix超时禁用
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false

#超时配置4秒，hystrix默认超时是1秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"